### PR TITLE
Created Skeleon of Seven Segment Display Device md file

### PR DESCRIPTION
**Pull request by cirqMoss**

### CODE REVIEW

**Comment by inetdavid** [comment]
Final AK2 is likely to replace this bare part with an HW-069 module which uses fewer pins and is much easier to use, but this will be handy for anyone working with the bare part included in the Beta kit.

**Review by inetdavid — COMMENTED** [review]
A number of examples using this part mentioned that folks may wish to insert 220 ohm resistors on each segment to limit current, just like we do with stand alone LEDs.  The part will work without them...but there's a high risk of segment burnout without something limiting current.  I'm NOT an electrical engineer, but I'm betting the data-sheet will show max current so this can be checked out for sure.

**Comment by inetdavid** [comment]
One sample comment:
"So, I followed this tutorial and in reality - my 4th digit started to burn out. Brightness decreased. But I found another tutorial that instead added 220 ohm resistors on pin 2-8. So be careful if you are going to do this tutorial and add 8x 220 ohm resistors"

**Comment by inetdavid** [comment]
Datasheet at http://www.xlitx.com/datasheet/5641AS.pdf.  I just don't know how to calculate the current vs. max current.  ;-)

**Comment by cirqMoss** [comment]
> Datasheet at http://www.xlitx.com/datasheet/5641AS.pdf. I just don't know how to calculate the current vs. max current. ;-)
So current would be directly proportional to voltage and resistance. We will need at least a 720Ω of resistance in series with the display to ensure the device does not go over the max current. But I believe that is for the whole setup each individual digit will need 220Ω I will put in a fritizing file that shows this

**Comment by cirqMoss** [comment]
Updated document to account for resistance and added fritzing file to show this.

**Pull request merged**
